name: Supabase

on:
  pull_request:
    paths:
      - "Sources/Supabase/**"
      - "Tests/Supabase/**"
      - ".github/workflows/supabase.yml"
  push:
    branches:
      - main
    paths:
      - "Sources/Supabase/**"
      - "Tests/Supabase/**"
      - ".github/workflows/supabase.yml"

concurrency:
  group: supabase-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Supabase
    strategy:
      fail-fast: false
      matrix:
        platform:
          - macOS
          - macOS,variant=Mac Catalyst
          - iOS Simulator,name=iPhone 15 Pro
          - tvOS Simulator,name=Apple TV
          - watchOS Simulator,name=Apple Watch Series 9 (41mm)
          - visionOS Simulator,name=Any visionOS Simulator Device
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Select Xcode 15.3
        run: sudo xcode-select -s /Applications/Xcode_15.3.app
      - name: Run tests
        run: PLATFORM="${{ matrix.platform }}" SCHEME=Supabase make test-library
  test-linux:
    name: Test Supabase (Linux)
    strategy:
      fail-fast: false
      matrix:
        swift-version: ["5.9", "5.10"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-deptch: 0
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift-version }}
      - run: make dot-env
      - name: Run tests
        run: swift test --filter SupabaseTests.